### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by sueskind** [Vision-CAIR/MammalNet#2]
Are the data already available? When I try to download  the videos with the command from the readme I get the following error:

```
$ aws s3 cp s3://mammalnet/trimmed_videos/ ./videos
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by junchen14** [comment]
hi, I am sorry for the late delay. Can you try it one more time with the command I provided? let me know if it works this time

**Comment by junchen14** [comment]
Hi I have updated the data files in aws s3. Now you can download it with wget. Can you give it a try now?

**Comment by sueskind** [comment]
Thank you, the download works now.
