### ISSUE TITLE
Issue Accessing MammalNet Dataset from S3 Bucket

### ISSUE THREAD

**Issue by rizarae-p** [Vision-CAIR/MammalNet#3]
Good day!

I'd like to express my appreciation for the work on MammalNet. The dataset appears to be of immense value to the community, and I'm keen on exploring it further for my research.

However, I've encountered a hiccup while trying to download the dataset. Following the provided AWS CLI command in the repository:

`aws s3 cp --recursive s3://mammalnet/full_videos/ .`

I received this error:

`fatal error: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
`

Additionally, I attempted to directly access the S3 bucket through the browser with the link:

[https://mammalnet.s3.amazonaws.com/full_videos/](https://mammalnet.s3.amazonaws.com/full_videos/)

Unfortunately, I was greeted with an `Access Denied `error.
```
<Error>
<script>window._wordtune_extension_installed = true;</script>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3Q38ARDY3YN4PKER</RequestId>
<HostId>nJn4/MqXXqn2mo1tA8hE6jl7Uy0ifDK1pK64o58aqEZP0O2qGV+H8WBrvAl5EVwiTEJSb2ggD5I=</HostId>
</Error>
```

Given these issues, I was wondering if it would be possible to either make the S3 bucket public or provide the necessary access credentials to download the dataset? 

Your assistance would greatly benefit my ongoing research and, I'm sure, many others in the community.

Thank you in advance for your time and help. 

Looking forward to accessing this promising dataset!

**Comment by junchen14** [comment]
thanks for informing me this issue.  I will fix this and will let you when it is ready

**Comment by junchen14** [comment]
Hi I have updated the data files in aws s3. Now you can download it with wget. Can you give it a try now?

**Comment by rizarae-p** [comment]
Thank you so much!
The download links are now working and I am currently downloading them.  :)

**Comment by Risk333** [comment]
Hey!

I was able to download full videos using: wget https://mammalnet.s3.amazonaws.com/full_video.tar.gz

However, I encountered an "Access Denied" error while trying to download the features file with wget https://mammalnet.s3.amazonaws.com/full_video_features/mammalnet_feature.tar.gz

Any insights on how to resolve this issue would be greatly appreciated.

Thanks!

**Comment by Risk333** [comment]
It's accessible now, Thank you so much.
